---
output:
  md_document:
    variant: markdown_github
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r}
knitr::opts_chunk$set(
  comment = "#>",
  fig.path = "show/README-",
  warning = FALSE
)
```


# omplotr: 'ggplot2' Based RNAseq Plot Function Collection

## Theme

`theme_onmath` is a ggplot theme used in almost all rnaseq plots.


```{r}
library(omplotr)
p <- ggplot(mtcars) + geom_point(aes(x = wt, y = mpg,colour = factor(gear)))
p + theme_onmath() + ggtitle("theme_onmath")
```

## Plot

functions to generate plot in ngs analysis

### QC

#### Reads GC distribution

```{r}
# Fastqc GC result
head(gc_test_data, 4)

# lineplot of GC distribution across Fastq file
gc_line_plot(gc_test_data)
```

#### Reads Quality barplot

```{r}
# Reads Quality result
# Bars of Quality <= 30 were marked with color 'dodgerblue', 
# Bars of Quality > 30 were marked with color 'navy'.
head(rq_test_data, 4)

# Reads Quality barplot
reads_quality_plot(rq_test_data)
```

### Quant

#### expression heatmap

```{r}
# expression matrix
head(exp_test_data, 4)

# sample information
head(test_sample_data, 4)

# plot expression heatmap
om_heatmap(exp_test_data, test_sample_data)
```
