#' Plot bwa mapping stats
#'
#' Plot bwa mapping stats summrized by samtools
#'
#' Mapping stats of each sample is generated by \code{samtools stats sorted.bam};
#'
#' Out stats is extracted using grep and sed command:
#'
#' \code{grep ^SN | cut -f 2,3 | sed -n '3p;7p;8p;9p;10p;11p;13p;15p;16p;19p;20p;23p;24p;25p;31p;32p;38p;40p'};
#'
#' Stats of all samples in analysis were merged into a single table.
#'
#' @param mapping_stats merged mapping stats file
#' @param sample_limit  sample number limit to show detail inform of each sample
#' @param out_prefix    output file prefix, default is NULL, don't output file
#' @examples
#' mapping_stats <- system.file("extdata", "all_sample.mapping.xls", package = "omplotr")
#' # show mapping summary
#' bwa_mapping_plot(mapping_stats, 5)
#' # show detail sample information
#' bwa_mapping_plot(mapping_stats, 10)

bwa_mapping_plot <- function(mapping_stats, sample_limit, out_prefix=NULL) {

  mapping_plot_order <- c('reads mapped', 'reads mapped and paired',
                          'reads properly paired', 'reads MQ0',
                          'non-primary alignments', 'reads unmapped')

  mapping_df <- read.delim(mapping_stats)
  sample_number <- dim(mapping_df)[2] - 1
  mapping_df$Item <- stringr::str_replace(mapping_df$Item, ":", "")
  mapping_per_df <- mapping_df[, -1]
  mapped_reads <- as.numeric(mapping_per_df[1, ])
  mapping_per_df <- as.data.frame(t(as.matrix(t(mapping_per_df)) / mapped_reads))
  mapping_per_df$Item <- mapping_df$Item

  mapping_per_df <- dplyr::filter(mapping_per_df, Item %in% mapping_plot_order)
  mapping_per_df$Item <- factor(mapping_per_df$Item,
                                levels = mapping_plot_order)
  m_mapping_per_df <- reshape2::melt(mapping_per_df, id.vars = c('Item'))

  if (sample_number < sample_limit) {
    map_plot <- ggplot(m_mapping_per_df, aes(Item, value, fill=variable)) +
      geom_bar(stat = 'identity', position = position_dodge(),
               color='black')
  } else {
    map_plot <- ggplot(m_mapping_per_df, aes(Item, value, fill=Item)) +
      geom_boxplot()
  }

  map_plot <- map_plot +
    theme_onmath() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
    scale_fill_brewer(palette = 'Set1') +
    xlab('') + ylab('Percentage of Reads') +
    guides(fill=guide_legend(title = 'SampleID')) +
    scale_y_continuous(labels = scales::percent)
  if (! is.null(out_prefix)) {
    out_dir <- dirname(out_prefix)
    path_name <- save_mkdir(out_dir)
    save_ggplot(ggplot_out = map_plot,
                output = out_prefix)
  }
  return(map_plot)
}
